spring:
  datasource:
    url: jdbc:postgresql://testdb.cxq2o08yw5mc.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Holaquehace.10
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: never